### ISSUE TITLE
Pin conflict with pHat DAC

### ISSUE THREAD

**Issue by benjaminfuchs** [bablokb/nerd-alarmclock#14]
Hi,
I want to use the nerd-alarmclock on my Pi Zero with the pHat DAC.
I needed to change the `/etc/asound.conf`, that was okay.
But it seems the GPIOs of the EncoderKnobThread are in conflict to the pHat DAC.
Here the PIN usage of it:
https://pinout.xyz/pinout/phat_dac
When I just run the nerd-alarmclock without the EncoderKnobThread it works.
I guess its `EK2_DT:  19` ... https://github.com/bablokb/nerd-alarmclock/blob/6689ec7f437de7fed93d24522bfe807c2af99f5a/files/etc/nerd-alarmclock.conf#L32 ... that makes the conflict since if I change that one to any other pin the sound works again with EncoderKnobThread active. 
Is it possible to use another GPIO pin for that or do I need to make a configuration to choose what to use PIN 19 for (sound/knob)?

**Comment by bablokb** [comment]
Hi, 
three things to do:
  - change the pin-number for EK2_DT in nerd-alarmclock.conf. Available/used pins are in doc/pins.md 
  - update /etc/gpio-poll.conf (add your replacement pin, remove pin 19)
  - update /usr/local/sbin/nerd-gpios.sh (ditto)

Three places is not very nice, we could probably merge nerd-gpios.sh into the startup code of nerd-alarmclock.py to get rid of at least one place.

**Comment by benjaminfuchs** [comment]
Should I change this for the whole project and properly mention pHat DAC to READMEs and PIN docu?

**Comment by benjaminfuchs** [comment]
I dump the `asound.conf` here so it is somewhere safe:
```
pcm.!default {
  type hw
  card 0
}
ctl.!default {
  type hw
  card 0
}
pcm.hifiberry {
    type softvol
    slave.pcm "plughw:0"
    control.name "Master"
    control.card 0
}
pcm.!default {
    type             plug
    slave.pcm       "hifiberry"
}
```

**Comment by bablokb** [comment]
Hi,
I suggest that you add a asound.conf.pHatDAC and mention this in the README.

**Comment by bablokb** [comment]
Added /etc/asound.conf.pHatDAC with commit bc3949b50b6495d4d0b8a365aad59fe2582b1ba5. Updated README.md with commit a75c8eb5b46b5168e071ae28e0721dc7ac11742d.
