### ISSUE TITLE
RTC 

### ISSUE THREAD

**Issue by Wuchta** [bablokb/nerd-alarmclock#16]
Hi I like the project. But I don't understand how the RTC is connected.
According to the pins it is connected to 1,3,5 and Ground. but 1,3,5 is already occupied by the 4LpHat. Thanks for your work.

**Comment by bablokb** [comment]
You need an expansion board to physically attach both the RTC and the 4LpHat. Both use the I2C bus (pins 3 and 5), but as long as the addresses don't overlap, this is no problem.
